// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG7wIkhtpm75uqM_T-KCD6xtDv_thlTh0',
    appId: '1:238778885352:web:cd8aa0fdd8b548a184155d',
    messagingSenderId: '238778885352',
    projectId: 'localresourcesharing',
    authDomain: 'localresourcesharing.firebaseapp.com',
    storageBucket: 'localresourcesharing.firebasestorage.app',
    measurementId: 'G-JXLQMBS78D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHRWAGmQiwSFvXo4Sm9nKt17LChB8Sjyk',
    appId: '1:238778885352:android:73b0529505e0dfce84155d',
    messagingSenderId: '238778885352',
    projectId: 'localresourcesharing',
    storageBucket: 'localresourcesharing.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6H9g2VVPg2K0HeqUWHrw37lmc6LtxOSE',
    appId: '1:238778885352:ios:b5f091702b0c176684155d',
    messagingSenderId: '238778885352',
    projectId: 'localresourcesharing',
    storageBucket: 'localresourcesharing.firebasestorage.app',
    iosBundleId: 'com.example.localResourceSharing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6H9g2VVPg2K0HeqUWHrw37lmc6LtxOSE',
    appId: '1:238778885352:ios:b5f091702b0c176684155d',
    messagingSenderId: '238778885352',
    projectId: 'localresourcesharing',
    storageBucket: 'localresourcesharing.firebasestorage.app',
    iosBundleId: 'com.example.localResourceSharing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG7wIkhtpm75uqM_T-KCD6xtDv_thlTh0',
    appId: '1:238778885352:web:ede972f9f4841acf84155d',
    messagingSenderId: '238778885352',
    projectId: 'localresourcesharing',
    authDomain: 'localresourcesharing.firebaseapp.com',
    storageBucket: 'localresourcesharing.firebasestorage.app',
    measurementId: 'G-KCJ9HNVEHQ',
  );
}
